name: Daily_bot2

on:
  push:
  schedule: 
        - cron: '0 9,15 * * *'
env:
    TOKEN1: ${{ secrets.TOKEN1 }}
    TOKEN2: ${{ secrets.TOKEN2 }}
    TOKEN3: ${{ secrets.TOKEN3 }}
    TOKEN4: ${{ secrets.TOKEN4 }}
    TOKEN5: ${{ secrets.TOKEN5}}



jobs:
    Daily-Run:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Install Dependencies
              run: pip install -r requirements.txt 
            - name: Run App
              run: python app2.py 
